#[Info]
site_name: Alex.Wang's Blog
site_author: Alex.Wang

#[UI]
theme: 
    name: material
    language: zh
    hljs_languages:
        - yaml
    logo: images/logo.png
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          accent: indigo
          toggle:
            icon: material/toggle-switch
            name: 切换至夜间模式
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black 
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: 切换至日间模式
    font:
        text: Roboto
        code: Roboto Mono
    icon:
        admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16


#[Plugins]
plugins:
    - blog

#[Navigation]
nav:
    - Blog:
        - blog/index.md
    - "控制理论":
        - '现代控制工程':
            - '参考书目': "control/modern_control/bibliography.md"
            - '数学基础':
                - 'Laplace变换与z变换': "control/modern_control/transform.md"
                - '矩阵基础': "control/modern_control/martix.md"
            - '控制系统的数学模型':
                - '传递函数模型': "control/modern_control/transfer.md"
                - '状态空间模型': "control/modern_control/state-variable.md"
        - '线性系统理论':
            - '参考书目': "control/linear_system/bibliography.md"
    - '嵌入式':
        - 'STM32': "embedded/STM32.md"
        - 'RTOS学习-[RT-Thread]': "embedded/RTOS-RT-Thread.md"
        - 'RTOS学习-[从0开始的RTOS]': "embedded/RTOS-DIY.md" 
    - '电子电路': 
        - '模拟电路':
            - '晶体管放大电路(BJT)': "analog_circuit/Transmitter-BJT.md"
            - '晶体管放大电路(FET)': "analog_circuit/Transmitter-FET.md"
        - '滤波器设计与实现': 
            - 'LC滤波器设计与实现': "analog_circuit/LC-Filter.md"
    - '微波天线':
        - '电磁场与电磁波': "microwave_antenna/Electromagnetics.md"
    - '关于': "about/about.md"

markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
